#!/usr/bin/env node
// GENERATED by scripts/project.mjs — do not edit. Source: statuslines/_shared/subagent-runtime.mjs
import { run } from "../../../statuslines/_shared/subagent-runtime.mjs";
run();
