#!/usr/bin/env node
// GENERATED by scripts/project.mjs — do not edit. Source: statuslines/verbose-hud/statusline.json
import { run } from "../../../statuslines/_shared/runtime.mjs";
import { fileURLToPath } from "node:url";
const descriptor = fileURLToPath(new URL("../../../statuslines/verbose-hud/statusline.json", import.meta.url));
run(descriptor, "hud");
