#!/usr/bin/env node
// projection-hooks.test.mjs — AG-0010 B3 + C4 projection tests.
//
// Dependency-free, TAP-ish (matches scripts/test-projection.mjs style). Two test
// families:
//
//   B3 (idempotency + event bindings): the tree is already projected and committed,
//   so we HASH the committed generated files, run `node scripts/project.mjs` once as
//   a subprocess, re-HASH, and assert the bytes are unchanged (idempotent projector).
//   We also run it a second time and re-hash to prove run-to-run stability. Then we
//   assert plugin.json's hooks block carries the expected event bindings and that
//   aegis.js contains the AEGIS:HOOKS-GEN region. The projector only ever rewrites
//   generated regions, so a green run leaves the committed tree byte-identical.
//
//   C4 (judgment-hook projection rules): using the EXTRACTED generateClaudeHooksBlock
//   from scripts/lib/hook-projection.mjs, assert prompt/agent dispatch shaping, the
//   enabled:false exclusion, that opencode/codex-only hooks never produce a Claude
//   prompt/agent entry, and that the four shipped judgment hooks are platforms:[claude].
//
// Run: node scripts/tests/projection-hooks.test.mjs  (exit 1 on any failure)
// Node 20+ stdlib only.

import { readFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import assert from "node:assert/strict";
import { generateClaudeHooksBlock } from "../lib/hook-projection.mjs";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const tests = [];
function test(name, fn) { tests.push({ name, fn }); }

function md5(path) {
  return createHash("md5").update(readFileSync(path)).digest("hex");
}

// Generated files the projector owns and must leave byte-stable on a no-change run.
const GENERATED = [
  join(REPO, ".claude-plugin", "plugin.json"),
  join(REPO, ".opencode", "plugins", "aegis.js"),
];

function runProjector() {
  execFileSync("node", [join(REPO, "scripts", "project.mjs")], {
    cwd: REPO,
    stdio: "ignore",
  });
}

// ── B3: idempotency across two subprocess runs ──────────────────────────────--

test("B3: projector is idempotent — generated files byte-identical across two runs", () => {
  const before = GENERATED.map(md5);
  runProjector();
  const after1 = GENERATED.map(md5);
  runProjector();
  const after2 = GENERATED.map(md5);
  assert.deepEqual(after1, before, "first run changed committed generated bytes (not idempotent vs committed tree)");
  assert.deepEqual(after2, after1, "second run differs from first (run-to-run instability)");
});

test("B3: plugin.json hooks block carries the expected event bindings", () => {
  const plugin = JSON.parse(readFileSync(GENERATED[0], "utf8"));
  const hooks = plugin.hooks ?? {};
  const events = Object.keys(hooks);
  for (const ev of ["SessionStart", "PreToolUse", "PreCompact", "PostCompact", "InstructionsLoaded"]) {
    assert.ok(events.includes(ev), `expected event ${ev} in plugin.json hooks, got: ${events.join(", ")}`);
  }
  // PreToolUse must contain the deny COMMAND hook binding.
  const pre = hooks.PreToolUse ?? [];
  const flat = pre.flatMap((e) => e.hooks ?? []);
  const hasDenyCommand = flat.some(
    (h) => h.type === "command" && /pre-tool-use-deny\.sh$/.test(h.command || ""),
  );
  assert.ok(hasDenyCommand, "PreToolUse must bind the pre-tool-use-deny command hook");
});

test("B3: aegis.js contains the AEGIS:HOOKS-GEN region", () => {
  const js = readFileSync(GENERATED[1], "utf8");
  assert.ok(js.includes("// >>> AEGIS:HOOKS-GEN"), "aegis.js missing AEGIS:HOOKS-GEN start marker");
  assert.ok(js.includes("// <<< AEGIS:HOOKS-GEN"), "aegis.js missing AEGIS:HOOKS-GEN end marker");
});

// ── C4: judgment-hook projection rules (via the extracted generator) ─────────--

function claudeIntent(overrides = {}) {
  return {
    kind: "hook",
    intent: "prompt-type",
    name: "z-judge",
    description: "x",
    visibility: "internal",
    platforms: ["claude"],
    "x-claude": { event: "PreToolUse", matcher: "Edit|Write|MultiEdit", dispatch: "prompt", prompt: "judge $ARGUMENTS" },
    ...overrides,
  };
}

test("C4: an ENABLED claude prompt-type hook emits a {type:'prompt'} entry", () => {
  const block = generateClaudeHooksBlock([claudeIntent({ name: "p-judge" })]);
  const entry = (block.PreToolUse ?? []).flatMap((e) => e.hooks ?? [])[0];
  assert.ok(entry, "expected a PreToolUse entry");
  assert.equal(entry.type, "prompt", `expected type prompt, got ${entry.type}`);
});

test("C4: an ENABLED claude agent-type hook emits a {type:'agent'} entry", () => {
  const agent = claudeIntent({
    name: "a-judge",
    intent: "agent-type",
    "x-claude": { event: "PreToolUse", matcher: "Bash", dispatch: "agent", prompt: "verify $ARGUMENTS" },
  });
  const block = generateClaudeHooksBlock([agent]);
  const entry = (block.PreToolUse ?? []).flatMap((e) => e.hooks ?? [])[0];
  assert.ok(entry, "expected a PreToolUse entry");
  assert.equal(entry.type, "agent", `expected type agent, got ${entry.type}`);
});

test("C4: enabled:false judgment hook is EXCLUDED from the block (D7/D11)", () => {
  const block = generateClaudeHooksBlock([claudeIntent({ name: "off-judge", enabled: false })]);
  assert.deepEqual(block, {}, "enabled:false hook must not appear in the generated block");
});

test("C4: an opencode/codex-only hook never produces a Claude prompt/agent entry", () => {
  const ocOnly = {
    kind: "hook", intent: "prompt-type", name: "oc-only", description: "x",
    visibility: "internal", platforms: ["opencode", "codex"],
    "x-opencode": { event: "session.start", handler: "noop" },
  };
  const block = generateClaudeHooksBlock([ocOnly]);
  assert.deepEqual(block, {}, "a non-claude hook must not appear in the Claude hooks block");
});

test("C4: the four shipped judgment hooks are platforms:[claude] and enabled:false", () => {
  const hooksDir = join(REPO, "hooks");
  const judgmentFiles = [
    "verify-no-secrets-touched.prompt.json",
    "no-silent-failures.prompt.json",
    "no-rationalization.prompt.json",
    "verification-before-completion.agent.json",
  ];
  for (const f of judgmentFiles) {
    const j = JSON.parse(readFileSync(join(hooksDir, f), "utf8"));
    assert.deepEqual(j.platforms, ["claude"], `${f}: expected platforms:[claude], got ${JSON.stringify(j.platforms)}`);
    assert.equal(j.enabled, false, `${f}: expected enabled:false (opt-in, D11), got ${JSON.stringify(j.enabled)}`);
  }
  // …and by construction they are absent from OpenCode/Codex output: not platforms-listed
  // there, and no .opencode/.codex hook-config carries an entry for them.
});

test("C4: shipped judgment hooks do not appear in the committed plugin.json hooks block", () => {
  const plugin = JSON.parse(readFileSync(GENERATED[0], "utf8"));
  const allPrompts = JSON.stringify(plugin.hooks ?? {});
  // The agent verifier's distinctive phrase must not be present (it ships enabled:false).
  assert.ok(!allPrompts.includes("verification gate spawned before a Bash command"),
    "verification-before-completion (enabled:false) must be absent from the default hooks block");
  assert.ok(!allPrompts.includes("secret-material gate"),
    "verify-no-secrets-touched (enabled:false) must be absent from the default hooks block");
});

// ── Runner ────────────────────────────────────────────────────────────────────
const runAll = async () => {
  let passed = 0, failed = 0;
  console.log("TAP version 13");
  console.log(`1..${tests.length}`);
  for (let i = 0; i < tests.length; i++) {
    const { name, fn } = tests[i];
    try {
      await fn();
      passed++;
      console.log(`ok ${i + 1} - ${name}`);
    } catch (err) {
      failed++;
      console.log(`not ok ${i + 1} - ${name}`);
      console.log(`  ---`);
      console.log(`  message: ${String(err && err.message).split("\n").join("\n    ")}`);
      console.log(`  ---`);
    }
  }
  console.log("");
  console.log(`# ${passed} passed, ${failed} failed (of ${tests.length})`);
  if (failed > 0) process.exit(1);
};

runAll();
